#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.62b95a36.name = "2022.09.16~ynh1"
    test_upgrade_from.7683dafdf9598fd6318bd353fc6ac20203a043c1.name = "3.202.4"
