#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.62b95a36.name = "2022.09.16~ynh1"
    test_upgrade_from.e8f144b902077d56c5240471564d33db9cf60d63.name = "Upgrade from 2023.01.26~ynh2"
