#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY CONFIG
#=================================================
ynh_script_progression "Modify configuring..."

ynh_replace --match="^FILES_SERVER_URL.*$" --replace="FILES_SERVER_URL=https://$new_domain$new_path/files" --file="$config_api_gateway"
ynh_store_file_checksum "$config_api_gateway"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
