#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source ../settings/scripts/ynh_add_swap
source /usr/share/yunohost/helpers

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-api-gateway.service"
ynh_restore "/etc/systemd/system/$app-auth.service"
ynh_restore "/etc/systemd/system/$app-auth-worker.service"
ynh_restore "/etc/systemd/system/$app-files.service"
ynh_restore "/etc/systemd/system/$app-syncing-server.service"
ynh_restore "/etc/systemd/system/$app-syncing-server-worker.service"

systemctl enable "$app-api-gateway.service" --quiet
systemctl enable "$app-auth.service" --quiet
systemctl enable "$app-auth-worker.service" --quiet
systemctl enable "$app-files.service" --quiet
systemctl enable "$app-syncing-server.service" --quiet
systemctl enable "$app-syncing-server-worker.service" --quiet

yunohost service add "$app-api-gateway" --description="Standard Notes - API Gateway" --log="/var/log/$app/api-gateway.log"
yunohost service add "$app-auth" --description="Standard Notes - Auth" --log="/var/log/$app/auth.log"
yunohost service add "$app-auth-worker" --description="Standard Notes - Auth - Worker" --log="/var/log/$app/auth-worker.log"
yunohost service add "$app-files" --description="Standard Notes - Files" --log="/var/log/$app/files.log"
yunohost service add "$app-syncing-server" --description="Standard Notes - Syncing Server" --log="/var/log/$app/syncing-server.log"
yunohost service add "$app-syncing-server-worker" --description="Standard Notes - Syncing Server - Worker" --log="/var/log/$app/syncing-server-worker.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/cron.d/$app"

ynh_restore "/var/log/$app/"

if ! ynh_in_ci_tests; then
    ynh_add_swap --size="$swap_needed"
fi

#=================================================
# MODIFY CONFIG
#=================================================
ynh_script_progression "Modify config files..."

# Redis Port
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_api_gateway"
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_auth"
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_auth_worker"
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_files"
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_syncing_server"
ynh_replace --match="^REDIS_URL.*$" --replace="REDIS_URL=redis://localhost:6379/$redis_db" --file="$config_syncing_server_worker"
# Syncing_Server Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_syncing_server" --file="$config_syncing_server"
ynh_replace --match="^SYNCING_SERVER_JS_URL.*$" --replace="SYNCING_SERVER_JS_URL=http://localhost:$port_syncing_server" --file="$config_api_gateway"
ynh_replace --match="^SYNCING_SERVER_URL.*$" --replace="SYNCING_SERVER_URL=http://localhost:$port_syncing_server" --file="$config_auth"
ynh_replace --match="^SYNCING_SERVER_URL.*$" --replace="SYNCING_SERVER_URL=http://localhost:$port_syncing_server" --file="$config_auth_worker"
# Syncing_Server_Worker Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_syncing_server_worker" --file="$config_syncing_server_worker"
# Auth Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_auth" --file="$config_auth"
ynh_replace --match="^AUTH_SERVER_URL.*$" --replace="AUTH_SERVER_URL=http://localhost:$port_auth" --file="$config_api_gateway"
ynh_replace --match="^AUTH_SERVER_URL.*$" --replace="AUTH_SERVER_URL=http://localhost:$port_auth" --file="$config_syncing_server"
ynh_replace --match="^AUTH_SERVER_URL.*$" --replace="AUTH_SERVER_URL=http://localhost:$port_auth" --file="$config_syncing_server_worker"
# Auth_Worker Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_auth_worker" --file="$config_auth_worker"
# API-Gateway Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_api_gateway" --file="$config_api_gateway"
ynh_replace_on_line --line="2" --match="proxy_pass.*$" --replace="proxy_pass http://127.0.0.1:$port_api_gateway/;" --file="/etc/nginx/conf.d/$domain.d/$app.conf"
# Files Port
ynh_replace --match="^PORT.*$" --replace="PORT=$port_files" --file="$config_files"
ynh_replace_on_line --line="17" --match="proxy_pass.*$" --replace="proxy_pass http://127.0.0.1:$port_files/;" --file="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's services..."

ynh_systemctl \
    --service="$app-api-gateway" \
    --action="start" \
    --log_path="/var/log/$app/api-gateway.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'
ynh_systemctl \
    --service="$app-auth" \
    --action="start" \
    --log_path="/var/log/$app/auth.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'
ynh_systemctl \
    --service="$app-auth-worker" \
    --action="start" \
    --log_path="/var/log/$app/auth-worker.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'
ynh_systemctl \
    --service="$app-files" \
    --action="start" \
    --log_path="/var/log/$app/files.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'
ynh_systemctl \
    --service="$app-syncing-server" \
    --action="start" \
    --log_path="/var/log/$app/syncing-server.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'
ynh_systemctl \
    --service="$app-syncing-server-worker" \
    --action="start" \
    --log_path="/var/log/$app/syncing-server-worker.log" \
    --wait_until='^.*Server started on port.*$|^.*Starting worker.*$'

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
